### PR TITLE
Updated Readme with login credentials.

### PR DESCRIPTION
**Pull request by tushartiwari7**
- Added Brief about E-Commerce App in Readme.
- Added Demo Login Credentials.

### CODE REVIEW

**Review by Bhakti199 — APPROVED** [review]
Well written Readme file, with all details.
This PR is good to merge.

**Review by Manju-sree — COMMENTED** [review]
good to see that you have done with readme file

**Review by Manju-sree — APPROVED** [review]
looks fine to merge

**Review by neetukumari4858 — APPROVED** [review]
Well written Readme file In this you have Explained each and Every thing About your Poject.It is good to see.

**Pull request merged**
